In [34]:
import numpy as np 
# Create a NumPy array of shape (3, 3) with all zeros.
# zeros function is used to create an array of given shape and fills it with zeros, and the size is given
x = np.zeros((3,3))
print("NumPy array of shape (3, 3) with all zeros:\n",x)

NumPy array of shape (3, 3) with all zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [2]:
# Generate a NumPy array of shape (5, 5) filled with random integers between 1 and 100.
y = np.random.randint(1,100,size=(5,5))  # HereSize is used to define the shape of the array
print("Numpy array of shape(5,5)  with random integers:\n",y)

Numpy array of shape(5,5)  with random integers:
 [[49 61 83  9 27]
 [45 67 18 89  1]
 [49  2 25 50 55]
 [ 2 35 57 39 14]
 [91 89 26 78 92]]


In [ ]:
# Create a 1D NumPy array of numbers from 10 to 50 with a step of 5.
# It is done using an inbuilt function of Numpy arange 
z = np.arange(10,50,5) # arange function gives a space of 5 as a common step for all the numbers in the given range
l = np.linspace(10,50,5) # linspace function generates 5 commonly spaced integers in the given range
print("Numpy array from 10 to 50 with a step of 5:",z)
print("Numpy array with functionm linespace:",l)

Numpy array from 10 to 50 with a atsep of 5: [10 15 20 25 30 35 40 45]
Numpy array with functionm linespace: [10. 20. 30. 40. 50.]


In [4]:
# How do you create an identity matrix of size 4?
identity_matrix = np.eye(4) # eye function is used to create an identity matrix and also assign the size/shape of the matrix
print("Identity matrix of size 3:\n",identity_matrix)

Identity matrix of size 3:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
# How do you flatten a 2D NumPy array into 1D?
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = array_2d.flatten() # flatten function is used to convert 2D array into 1D
print("Flattened 1D array:", flattened_array)

Flattened 1D array: [1 2 3 4 5 6]


In [6]:
# Extract all even numbers from a NumPy array.
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("The Even Numbers in the given array are:", array[array % 2 == 0]) # Using boolean indexing to extract even

The Even Numbers in the given array are: [ 2  4  6  8 10]


In [7]:
# Replace all values greater than 50 in a NumPy array with 0.
array = np.array([10, 20, 30, 60, 70, 80])
print(np.where(array > 50,0,array)) # Using np.where to replace values greater than 50 with 0

[10 20 30  0  0  0]


In [8]:
# Find the maximum, minimum, mean, median, and standard deviation of a NumPy array.
arr = np.array([1, 2, 3, 4, 5])
print("Maximum:", np.max(arr)) # max function to find maximum value
print("Minimum:", np.min(arr)) # min function to find minimum value
print("Mean:", np.mean(arr)) # mean function to find mean value
print("Median:", np.median(arr)) # median function to find median value
print("Standard Deviation:", np.std(arr)) # std function to find standard deviation

Maximum: 5
Minimum: 1
Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951


In [9]:
# How do you perform element-wise addition, subtraction, multiplication, and division between two arrays?
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Element-wise Addition:", a + b) # Addition
print("Element-wise Subtraction:",a - b) # Subtraction
print("Element-wise Multiplication:",a * b) # Multiplication
print("Element-wise Division:",a / b) # Division

Element-wise Addition: [5 7 9]
Element-wise Subtraction: [-3 -3 -3]
Element-wise Multiplication: [ 4 10 18]
Element-wise Division: [0.25 0.4  0.5 ]


In [10]:
# Normalize a NumPy array (values between 0 and 1).
array = np.array([10,20,30,40,50])
normalize_array = (array - np.min(array)) / (np.max(array) - np.min(array)) # Normalization formula
print("Normalized array:",normalize_array)

Normalized array: [0.   0.25 0.5  0.75 1.  ]


In [11]:
# Get the indices of the maximum and minimum values in a NumPy arra
array = np.array([10, 20, 5, 40, 15])
max_index = np.argmax(array) # argmax function to get the index of maximum value
min_index = np.argmin(array) # argmin function to get the index of minimum value
print("Index of maximum value:", max_index, "and the value is:", array[max_index])
print("Index of minimum value:", min_index, "and the value is:", array[min_index])

Index of maximum value: 3 and the value is: 40
Index of minimum value: 2 and the value is: 5


In [12]:
# How do you sort a NumPy array in ascending and descending order?
array = np.array([5, 2, 9, 1, 5, 6])
print("Array in ascending order:", np.sort(array)) # sort function to sort the array in ascending order
print("Array in descending order:", np.sort(array)[::-1]) # sort function with slicing to sort the array in descending order

Array in ascending order: [1 2 5 5 6 9]
Array in descending order: [9 6 5 5 2 1]


In [13]:
# How do you find unique elements in an array and their counts?
array = np.array([1, 2, 2, 3, 4, 4, 4, 5])
unique,counts = np.unique(array, return_counts=True) # unique function to find unique elements and their counts
print("Unique elements:", unique)
print("Counts of unique elements:", counts)

Unique elements: [1 2 3 4 5]
Counts of unique elements: [1 2 1 3 1]


In [14]:
# Split a NumPy array into multiple sub-arrays.
array = np.array([1, 2, 3, 4, 5, 6])
sub_arrays = np.array_split(array, 3) # array_split function to split the array
print("Sub-arrays:", sub_arrays)

Sub-arrays: [array([1, 2]), array([3, 4]), array([5, 6])]


In [15]:
# Stack two NumPy arrays vertically and horizontally.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
print("Vertically stacked arrays:\n", np.vstack((array1, array2))) # vstack function to stack arrays vertically
print("Horizontally stacked arrays:\n", np.hstack((array1, array2))) # hstack function to stack arrays horizontally

Vertically stacked arrays:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontally stacked arrays:
 [[1 2 5 6]
 [3 4 7 8]]


In [16]:
# How do you invert a matrix using NumPy?
array = np.array([[1, 2], [3, 4]])
print("Inverse of the matrix:\n", np.linalg.inv(array)) # linalg.inv function to find the inverse of the matrix

Inverse of the matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [17]:
# Create a 3×3 matrix filled with the number 5?
matrix_3x3 = np.full((3, 3), 5) # full function to create a matrix of given shape and fills it with the specified number
print("3x3 matrix filled with the number 5:\n", matrix_3x3)

3x3 matrix filled with the number 5:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]


In [18]:
# Generate a sequence of even numbers between 2 and 40?
even_numbers = np.arange(2, 41, 2) # arange function to generate even numbers in the given range with a step of 2
print("Even numbers between 2 and 40:", even_numbers)

Even numbers between 2 and 40: [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [19]:
# Create an array of 10 random numbers between 0 and 1?
random_numbers = np.random.rand(10) # rand function to generate random numbers between 0 and 1
print("Array of 10 random numbers between 0 and 1:", random_numbers)

Array of 10 random numbers between 0 and 1: [0.70859456 0.63361732 0.469249   0.95070985 0.60907604 0.36585854
 0.21339314 0.1900389  0.87634491 0.91676796]


In [20]:
# Retrieve the last 3 elements from a NumPy array?
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("The last three elements of the array are: ", array[-3:]) # Slicing to get the last 3 elements of the array

The last three elements of the array are:  [ 8  9 10]


In [21]:
# Slice the 2nd and 3rd columns from a 4×4 matrix?
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])  
print("The 2nd and 3rd columns from the 4x4 matrix are:\n", array[:, 1:3]) # Slicing to get the 2nd and 3rd columns

The 2nd and 3rd columns from the 4x4 matrix are:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [22]:
# Retrieve the last 3 elements from a NumPy array.
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("The last three elements of the array are: ", array[-3:]) # Slicing to get the last 3 elements of the array

The last three elements of the array are:  [ 8  9 10]


In [23]:
# Compute the cumulative sum of numbers from 1 to 10.
array = np.array([1,2,3,4,5,6,7,8,9,10])
print("Cumulative sum of numbers from 1 to 10:", np.cumsum(array)) # cumsum function to compute cumulative sum

Cumulative sum of numbers from 1 to 10: [ 1  3  6 10 15 21 28 36 45 55]


In [24]:
# Find the product of all elements in an array.
array = np.array([1, 2, 3, 4, 5])
print("Product of all elements in the array:", np.prod(array)) # prod function to find the product of all elements

Product of all elements in the array: 120


In [25]:
# Count how many elements in an array are greater than its mean ?
array = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(array) # mean function to calculate the mean of the array
count_greater_than_mean = np.sum(array > mean_value) # Boolean indexing and sum function
print("Number of elements greater than the mean:", count_greater_than_mean)

Number of elements greater than the mean: 2


In [26]:
# Invert the values in a binary array (0→1, 1→0).
array = np.array([0, 1, 0, 1, 1, 0])
Binary_Inverted_array = 1 - array # Inverting binary values by subtracting from 1
print("Inverted binary array:", Binary_Inverted_array)

Inverted binary array: [1 0 1 0 0 1]


In [35]:
# Print Numpy Configuration and Version
np.version
np.show_config

<function numpy.__config__.show(mode='stdout')>

In [41]:
# A null vector of size 10 and the memory size of an array
null_vector = np.zeros(10)
print("The memory size of an array: ",null_vector.__sizeof__())

The memory size of an array:  192


In [43]:
# How to get the documentation of the numpy and add function from the command line?
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [44]:
# Create a null Vector of size 10 but the fifth value which is 1
null = np.zeros(10)
null[4] = 1
print(null)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
